### ISSUE TITLE
LeastSquareSLIM index outside of bounds of the array

### ISSUE THREAD

**Issue by Djoels** [zenogantner/MyMediaLite#474]
Another error in windows: 

Set random seed to 123.
loading_time 25.2
memory 200
training data: 254083 users, 233917 items, 9346546 events, sparsity 99.98427
test data:     217574 users, 184827 items, 2335071 events, sparsity 99.99419
LeastSquareSLIM reg_l1=0.001 reg_l2=0.001 num_iter=5 K=100

  **************************************************************************************
  *** An uncaught exception occured. Please report the problem in our issue tracker: ***
  *** https://github.com/zenogantner/MyMediaLite/issues ***
  *** MyMediaLite 3.12                                                               ***
  **************************************************************************************
Array dimensions exceeded supported range.   at MyMediaLite.DataType.Matrix`1..ctor(Int32 dim1, Int32 dim2)
   at MyMediaLite.ItemRecommendation.SLIM.InitModel()
   at MyMediaLite.ItemRecommendation.LeastSquareSLIM.InitModel()
   at MyMediaLite.ItemRecommendation.LeastSquareSLIM.Train()
   at ItemRecommendation.Run(String[] args)
   at ItemRecommendation.Main(String[] args)
Terminate on unhandled exception.

Op dinsdag 14 maart 2017 14:07:09 UTC+1 schreef Djoels:
Command:
"
module load MyMediaLite

item_recommendation --recommender=LeastSquareSLIM  --recommender-options="reg_l1=0.01 reg_l2=0.001 num_iter=5 K=50" \
    --num-test-users=20000 --test-ratio=0.2 --random-seed=123 \
    --find-iter=1 --num-iter=1 --max-iter=5  \
    --measures="AUC,prec@10,MAP,recall@10,NDCG,MRR" \
    --training-file=data/MyMediaLite_ItemRecommender.tsv > MML_06_LeastSquareSLIM.log 2>&1  
"

produces the following error:

Set random seed to 123.
loading_time 31.53
memory 203
training data: 254083 users, 233917 items, 9346546 events, sparsity 99.98427
test data:     217574 users, 184827 items, 2335071 events, sparsity 99.99419
LeastSquareSLIM reg_l1=0.01 reg_l2=0.001 num_iter=1 K=50

Index was outside the bounds of the array.  at MyMediaLite.DataType.Matrix`1[T].set_Item (System.Int32 i, System.Int32 j, T value) [0x00088] in /tmp/vsc40003/easybuild/MyMediaLite/3.11/intel-2016b/zenogantner-MyMediaLite-b9d0478/src/MyMediaLite/DataType/Matrix.cs:149 
  at MyMediaLite.ItemRecommendation.SLIM.InitModel () [0x00039] in /tmp/vsc40003/easybuild/MyMediaLite/3.11/intel-2016b/zenogantner-MyMediaLite-b9d0478/src/MyMediaLite/ItemRecommendation/SLIM.cs:79 
  at MyMediaLite.ItemRecommendation.LeastSquareSLIM.InitModel () [0x00000] in /tmp/vsc40003/easybuild/MyMediaLite/3.11/intel-2016b/zenogantner-MyMediaLite-b9d0478/src/MyMediaLite/ItemRecommendation/LeastSquareSLIM.cs:78 
  at MyMediaLite.ItemRecommendation.LeastSquareSLIM.Train () [0x00000] in /tmp/vsc40003/easybuild/MyMediaLite/3.11/intel-2016b/zenogantner-MyMediaLite-b9d0478/src/MyMediaLite/ItemRecommendation/LeastSquareSLIM.cs:92 
  at ItemRecommendation.Train () [0x00000] in /tmp/vsc40003/easybuild/MyMediaLite/3.11/intel-2016b/zenogantner-MyMediaLite-b9d0478/src/Programs/ItemRecommendation/ItemRecommendation.cs:185 
  at ItemRecommendation.Run (System.String[] args) [0x0011b] in /tmp/vsc40003/easybuild/MyMediaLite/3.11/intel-2016b/zenogantner-MyMediaLite-b9d0478/src/Programs/ItemRecommendation/ItemRecommendation.cs:222 
  at ItemRecommendation.Main (System.String[] args) [0x00006] in /tmp/vsc40003/easybuild/MyMediaLite/3.11/intel-2016b/zenogantner-MyMediaLite-b9d0478/src/Programs/ItemRecommendation/ItemRecommendation.cs:151 
Terminate on unhandled exception.

**Comment by Djoels** [comment]
Same problem for other SLIM method (BPRSLIM):
Set random seed to 123.
loading_time 25.66
memory 200
training data: 254083 users, 233917 items, 9346546 events, sparsity 99.98427
test data:     217574 users, 184827 items, 2335071 events, sparsity 99.99419
BPRSLIM reg_i=0.01 reg_j=0.01 num_iter=5 learn_rate=0.001 uniform_user_sampling=True with_replacement=False update_j=True

  **************************************************************************************
  *** An uncaught exception occured. Please report the problem in our issue tracker: ***
  *** https://github.com/zenogantner/MyMediaLite/issues ***
  *** MyMediaLite 3.12                                                               ***
  **************************************************************************************
Array dimensions exceeded supported range.   at MyMediaLite.DataType.Matrix`1..ctor(Int32 dim1, Int32 dim2)
   at MyMediaLite.ItemRecommendation.SLIM.InitModel()
   at MyMediaLite.ItemRecommendation.BPRSLIM.Train()
   at ItemRecommendation.Run(String[] args)
   at ItemRecommendation.Main(String[] args)
Terminate on unhandled exception.
